/* Generated by Goblint-CIL v. 2.0.9 */
/* print_CIL_Input is false */

/*
 * This is a RANDOMLY GENERATED PROGRAM.
 *
 * Generator: csmith 2.4.0
 * Git version: unknown
 * Options: (none)
 * Seed: 16277902899234726345
 */

#include "csmith.h"

/* --- Struct/Union Declarations --- */
/* --- GLOBAL VARIABLES --- */

static int32_t g_3[1] = { -6};
/* --- FORWARD DECLARATIONS --- */

/* --- FUNCTIONS --- */
/* ------------------------------------------ */
/* 
 * reads : g_3
 * writes: g_3
 */

static int32_t func_1(void) ;
static int32_t func_1(void) 
{ 
  int32_t *l_4 = & g_3[0];
  int32_t *l_5 = & g_3[0];
  int32_t *l_7[5][4] = {{& g_3[0], (int32_t *)((void *)0), & g_3[0], (int32_t *)((void *)0)}, {& g_3[0], (int32_t *)((void *)0), & g_3[0], (int32_t *)((void *)0)}, {& g_3[0], (int32_t *)((void *)0), & g_3[0], (int32_t *)((void *)0)}, {& g_3[0], (int32_t *)((void *)0), & g_3[0], (int32_t *)((void *)0)}, {& g_3[0], (int32_t *)((void *)0), & g_3[0], (int32_t *)((void *)0)}};
  int32_t l_8 = 841897070;
  uint64_t l_9 = 4317115725046496791UL;

  l_9 --;
  for (l_8 = 3; l_8 >= 0; l_8 --) { return (g_3[0]);
  }
  *l_4 = (unsigned long )l_5 == (unsigned long )((void *)0);
  return (g_3[0]);
}
/* ---------------------------------------- */

int main(int argc , char **argv ) 
{ 
  int i ;
  int print_hash_value = 0;
  int tmp ;

  if (argc == 2) { tmp = strcmp((char const *)*(argv + 1), (char const *)"1");
    if (tmp == 0) { print_hash_value = 1;
    }
  }
  platform_main_begin();
  crc32_gentab();
  func_1();
  for (i = 0; i < 1; i ++) { transparent_crc((uint64_t )g_3[i], "g_3[i]", print_hash_value);
    if (print_hash_value) {
      printf((char const */* __restrict */)"index = [%d]\n", i);
    }
  }
  platform_main_end((uint32_t )((unsigned long )crc32_context ^ 0xFFFFFFFFUL), print_hash_value);
  return (0);
}
/************************ statistics *************************
XXX max struct depth: 0
breakdown:
   depth: 0, occurrence: 2
XXX total union variables: 0

XXX non-zero bitfields defined in structs: 0
XXX zero bitfields defined in structs: 0
XXX const bitfields defined in structs: 0
XXX volatile bitfields defined in structs: 0
XXX structs with bitfields in the program: 0
breakdown:
XXX full-bitfields structs in the program: 0
breakdown:
XXX times a bitfields struct's address is taken: 0
XXX times a bitfields struct on LHS: 0
XXX times a bitfields struct on RHS: 0
XXX times a single bitfield on LHS: 0
XXX times a single bitfield on RHS: 0

XXX max expression depth: 2
breakdown:
   depth: 1, occurrence: 5
   depth: 2, occurrence: 2

XXX total number of pointers: 5

XXX times a variable address is taken: 9
XXX times a pointer is dereferenced on RHS: 0
breakdown:
XXX times a pointer is dereferenced on LHS: 1
breakdown:
   depth: 1, occurrence: 1
XXX times a pointer is compared with null: 1
XXX times a pointer is compared with address of another variable: 0
XXX times a pointer is compared with another pointer: 0
XXX times a pointer is qualified to be dereferenced: 292

XXX max dereference level: 1
breakdown:
   level: 0, occurrence: 0
   level: 1, occurrence: 1
XXX number of pointers point to pointers: 0
XXX number of pointers point to scalars: 5
XXX number of pointers point to structs: 0
XXX percent of pointers has null in alias set: 20
XXX average alias set size: 1.2

XXX times a non-volatile is read: 4
XXX times a non-volatile is write: 4
XXX times a volatile is read: 0
XXX times read thru a pointer: 0
XXX times a volatile is write: 0
XXX times written thru a pointer: 0
XXX times a volatile is available for access: 0
XXX percentage of non-volatile access: 100

XXX forward jumps: 0
XXX backward jumps: 0

XXX stmts: 5
XXX max block depth: 1
breakdown:
   depth: 0, occurrence: 4
   depth: 1, occurrence: 1

XXX percentage a fresh-made variable is used: 3.45
XXX percentage an existing variable is used: 96.6
FYI: the random generator makes assumptions about the integer size. See platform.info for more details.
XXX total OOB instances added: 0
********************* end of statistics **********************/
